version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: mongo
    ports:
      - "27017:27017"
